scalar DateTime

type User {
  uuid: ID!
  firstName: String!
  lastName: String!
  email: String!
  verificationToken: String
  createdAt: DateTime!
  updatedAt: DateTime!
}

input CreateUserInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

input UpdateUserInput {
  firstName: String
  lastName: String
  email: String
  password: String
  verifiedEmail: Boolean
  verificationToken: String
}

type Query {
  user(uuid: ID!): User
  users: [User!]!
  getUserByEmail(email: String!): User
  me: User
}

type Mutation {
  createUser(data: CreateUserInput!): User!
  updateUser(uuid: ID!, data: UpdateUserInput!): User!
  deleteUser(uuid: ID!): Boolean!
  verifyEmail(token: String!): Boolean!
}
