scalar DateTime

type Member {
  uuid: ID!
  firstName: String!
  lastName: String!
  joinDate: DateTime!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input CreateMemberInput {
  firstName: String!
  lastName: String!
}

input UpdateMemberInput {
  firstName: String
  lastName: String
}

type Query {
  member(uuid: ID!): Member
  members: [Member!]!
}

type Mutation {
  createMember(data: CreateMemberInput!): Member!
  updateMember(uuid: String!, data: UpdateMemberInput!): Member!
  deleteMember(uuid: String!): Member!
}

