mutation Login($data: ValidateUserInput!) {
  login(data: $data) {
    message
  }
}

mutation CreateUser($data: CreateUserInput!) {
  createUser(data: $data) {
    uuid
    email
    firstName
    lastName
  }
}

mutation UpdateUser($uuid: String!, $data: UpdateUserInput!) {
  updateUser(uuid: $uuid, data: $data) {
    uuid
    email
    firstName
    lastName
  }
}

mutation DeleteUser($uuid: String!) {
  deleteUser(uuid: $uuid)
}

mutation VerifyEmail($token: String!) {
  verifyEmail(token: $token)
}

mutation ResendVerificationEmail($email: String!) {
  resendVerificationEmail(email: $email)
}

query GetUser($uuid: String!) {
  user(uuid: $uuid) {
    uuid
    email
    firstName
    lastName
  }
}

query GetUsers {
  users {
    uuid
    email
    firstName
    lastName
  }
}

query GetUserByEmail($email: String!) {
  getUserByEmail(email: $email) {
    uuid
    email
    firstName
    lastName
  }
}

query Me {
  me {
    uuid
    email
    firstName
    lastName
  }
}

mutation Logout {
  logout
}

mutation RefreshAccessToken {
  refreshAccessToken
}
